// app/javascript/controllers/index.js
// This file is auto-generated by stimulus:manifest:update
import { application } from "./application"

import BookingController from "./booking_controller"
import FlashController from "./flash_controller"
import NotificationController from "./notification_controller"
import SearchController from "./search_controller"

application.register("booking", BookingController)
application.register("flash", FlashController)
application.register("notification", NotificationController)
application.register("search", SearchController)
